import {questions,complete,score} from './questions.js';
const key='lcc-english-test-v1';let state={answers:Array(25).fill(null),page:0,submitted:false};
try{const saved=JSON.parse(localStorage.getItem(key));if(saved&&Array.isArray(saved.answers)&&saved.answers.length===25){state.answers=saved.answers.map((v,i)=>Number.isInteger(v)&&v>=0&&v<questions[i][1].length?v:null);state.page=Number.isInteger(saved.page)?Math.max(0,Math.min(4,saved.page)):0;state.submitted=saved.submitted===true&&complete(state.answers);}}catch{}
const main=document.querySelector('main');let storageOK=true;
function save(){try{localStorage.setItem(key,JSON.stringify(state));}catch{storageOK=false;}}
function pageComplete(){return state.answers.slice(state.page*5,state.page*5+5).every(v=>v!==null);}
function moveFocus(){main.focus();window.scrollTo({top:0,behavior:'instant'});}
function render(){if(state.submitted){result();return;}document.querySelector('#title').innerHTML='测试你的英语<span>——中小学生</span>';
main.innerHTML=`<div class="progress" role="progressbar" aria-label="测试页数" aria-valuenow="${state.page+1}" aria-valuemin="0" aria-valuemax="5"><div style="width:${(state.page+1)*20}%"></div></div><p class="page">Page ${state.page+1} of 5</p><p class="count">已答 <span id="answered">${state.answers.filter(v=>v!==null).length}</span> / 25 题</p><p class="instructions" lang="en">For the questions below, please choose the best option to complete the sentence or conversation.</p><form id="quiz"><div id="questions"></div><p class="hint" id="hint" aria-live="polite"></p><div class="nav"><button type="button" id="previous" ${state.page===0?'disabled':''}>‹ Previous</button><button class="primary" id="next" type="submit">${state.page===4?'Get result':'Next'} ›</button></div></form><p class="saved">${storageOK?'答题进度自动保存在当前浏览器':'当前浏览器无法保存进度，请勿关闭页面'}</p>`;
const target=document.querySelector('#questions');questions.slice(state.page*5,state.page*5+5).forEach((q,j)=>{const i=state.page*5+j;const field=document.createElement('fieldset');const legend=document.createElement('legend');legend.textContent=`${i+1}) ${q[0]}`;field.append(legend);q[1].forEach((text,k)=>{const label=document.createElement('label');const radio=document.createElement('input');radio.type='radio';radio.name=`question-${i}`;radio.value=k;radio.checked=state.answers[i]===k;radio.addEventListener('change',()=>{state.answers[i]=k;save();update();});const span=document.createElement('span');span.textContent=text;label.append(radio,span);field.append(label);});target.append(field);});
document.querySelector('#previous').onclick=()=>{if(state.page>0){state.page--;save();render();moveFocus();}};document.querySelector('#quiz').onsubmit=e=>{e.preventDefault();if(!pageComplete())return;if(state.page<4)state.page++;else if(complete(state.answers))state.submitted=true;save();render();moveFocus();};update();}
function update(){document.querySelector('#next').disabled=!pageComplete();document.querySelector('#answered').textContent=state.answers.filter(v=>v!==null).length;document.querySelector('#hint').textContent=pageComplete()?(state.page===4?'已完成全部题目，可以查看成绩。':'本页已完成，可以继续。'):'You must answer all the questions to continue.';}
function result(){const n=score(state.answers);document.querySelector('#title').textContent='Test your English — results';main.innerHTML=`<section class="result"><span class="eyebrow">TEST COMPLETED</span><h2>你已完成测试，很棒！</h2><div class="scorebox"><div>你的得分</div><strong>${n}</strong><span>/ 25</span><p>答对 ${n} 题 · 答错 ${25-n} 题 · 正确率 ${n*4}%</p></div><p class="result-note">每题 1 分，满分 25 分。此分数反映本次题目的作答情况，可供老师了解你的英语基础。<br>本测试未覆盖听力、口语与写作，不直接换算为正式英语等级。</p><div class="result-actions"><button class="primary" id="restart">重新测试</button><button id="print">打印 / 保存成绩</button></div><details><summary>查看答题记录</summary><div id="review"></div></details></section>`;
questions.forEach((q,i)=>{const row=document.createElement('div');row.className='review';const title=document.createElement('b');title.textContent=`${i+1}) ${q[0]}`;const answer=document.createElement('div');const right=state.answers[i]===q[2];answer.className=right?'correct':'incorrect';answer.textContent=`${right?'✓':'✗'} 你的答案：${q[1][state.answers[i]]}`;row.append(title,answer);if(!right){const correct=document.createElement('div');correct.textContent=`参考答案：${q[1][q[2]]}`;row.append(correct);}document.querySelector('#review').append(row);});document.querySelector('#print').onclick=()=>window.print();document.querySelector('#restart').onclick=()=>{if(!window.confirm('重新测试将清除本次答题记录，是否继续？'))return;state={answers:Array(25).fill(null),page:0,submitted:false};save();render();moveFocus();};}
render();
